package hr.fer.zemris.java.custom.scripting.lexer;

/**
 * Possible token types generated by smart script lexer.
 * 
 * @author Ivica Brebrek
 * @version 1.0  (27.3.2016.)
 */
public enum SSTokenType {
	/** Token is text(outside tags) */
	TEXT,
	/** Token is string(inside tags) */
	STRING,
	/** Token is decimal number */
	NUMBER_DECIMAL,
	/** Token is non-decimal number */
	NUMBER_INTEGER,
	/** Token is a symbol */
	SYMBOL, //NOTE: lexer will put = in this type, parser will know the difference
	/** Token is variable */
	VARIABLE, //NOTE: lexer will put FOR and END in this type, parser will know the difference
	/** Token is function */
	FUNCTION,
	/** Token represents start of a new tag */
	TAG_START,
	/** Token represents end of a tag */
	TAG_END,
	/** Token represents end of file */
	EOF;
}
